# Student Activity: Solving Rank of a Matrix, Systems of Equations, and Matrix Operations



In [1]:
import numpy as np

## Problem 1: Rank of a Matrix

In [2]:
# Define the matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the rank
rank = np.linalg.matrix_rank(A)

print("Matrix A:")
print(A)
print(f"\nRank of matrix A: {rank}")

# Explanation
print("\nExplanation:")
print("The rank of this matrix is 2 because:")
print("1. It has 3 rows, but the third row is a linear combination of the first two.")
print("2. Specifically, row3 = 2 * row2 - row1")
print("3. This means there are only 2 linearly independent rows or columns.")

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank of matrix A: 2

Explanation:
The rank of this matrix is 2 because:
1. It has 3 rows, but the third row is a linear combination of the first two.
2. Specifically, row3 = 2 * row2 - row1
3. This means there are only 2 linearly independent rows or columns.


## Problem 2: Solving Systems of Equations Using Matrix Inverse (3x3)

In [3]:
# Define the coefficient matrix
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

# Define the constant vector
b = np.array([8, -11, -3])

# Check if the matrix is invertible
if np.linalg.det(A) != 0:
    # Solve the system
    x = np.linalg.inv(A).dot(b)
    print("Solution:")
    print(f"x = {x[0]:.2f}")
    print(f"y = {x[1]:.2f}")
    print(f"z = {x[2]:.2f}")

    # Verify the solution
    print("\nVerification:")
    print(f"Ax = {A.dot(x)}")
    print(f"b  = {b}")
else:
    print("Matrix A is not invertible. No unique solution.")

# Explanation
print("\nExplanation:")
print("1. We first check if the matrix is invertible by calculating its determinant.")
print("2. If invertible, we use the formula x = A^(-1) * b to solve the system.")
print("3. We verify the solution by checking if Ax equals b.")

Solution:
x = 2.00
y = 3.00
z = -1.00

Verification:
Ax = [  8. -11.  -3.]
b  = [  8 -11  -3]

Explanation:
1. We first check if the matrix is invertible by calculating its determinant.
2. If invertible, we use the formula x = A^(-1) * b to solve the system.
3. We verify the solution by checking if Ax equals b.


## Problem 3: Matrix Addition for Different Dimensions

In [4]:
def matrix_addition(A, B):
    """Perform matrix addition for two matrices of the same dimension."""
    if A.shape != B.shape:
        raise ValueError("Matrices must have the same dimensions for addition.")
    return A + B

# 4x4 matrix addition
A_4x4 = np.random.randint(1, 10, size=(4, 4))
B_4x4 = np.random.randint(1, 10, size=(4, 4))
result_4x4 = matrix_addition(A_4x4, B_4x4)

print("4x4 Matrix Addition:")
print("Matrix A:")
print(A_4x4)
print("\nMatrix B:")
print(B_4x4)
print("\nResult (A + B):")
print(result_4x4)

# 5x5 matrix addition
A_5x5 = np.random.randint(1, 10, size=(5, 5))
B_5x5 = np.random.randint(1, 10, size=(5, 5))
result_5x5 = matrix_addition(A_5x5, B_5x5)

print("\n5x5 Matrix Addition:")
print("Matrix A:")
print(A_5x5)
print("\nMatrix B:")
print(B_5x5)
print("\nResult (A + B):")
print(result_5x5)

# Explanation
print("\nExplanation:")
print("1. Matrix addition is performed element-wise.")
print("2. The matrices must have the same dimensions for addition to be possible.")
print("3. The result matrix has the same dimensions as the input matrices.")
print("4. This method works for any n×n matrices, as long as they have the same dimensions.")

4x4 Matrix Addition:
Matrix A:
[[5 3 3 6]
 [7 5 3 2]
 [1 4 8 4]
 [3 6 4 2]]

Matrix B:
[[4 4 9 5]
 [6 7 4 6]
 [1 1 1 9]
 [6 2 4 6]]

Result (A + B):
[[ 9  7 12 11]
 [13 12  7  8]
 [ 2  5  9 13]
 [ 9  8  8  8]]

5x5 Matrix Addition:
Matrix A:
[[7 4 4 5 4]
 [5 2 4 1 9]
 [9 9 4 7 1]
 [1 5 7 7 1]
 [3 8 2 9 8]]

Matrix B:
[[9 8 4 3 5]
 [3 4 3 2 3]
 [9 5 3 3 5]
 [8 1 8 3 5]
 [7 5 5 3 9]]

Result (A + B):
[[16 12  8  8  9]
 [ 8  6  7  3 12]
 [18 14  7 10  6]
 [ 9  6 15 10  6]
 [10 13  7 12 17]]

Explanation:
1. Matrix addition is performed element-wise.
2. The matrices must have the same dimensions for addition to be possible.
3. The result matrix has the same dimensions as the input matrices.
4. This method works for any n×n matrices, as long as they have the same dimensions.


## Problem 4: Applying Python to Solve Related Matrix Problems

In [5]:
def matrix_operations(A, B):
    """Perform various matrix operations on two matrices."""
    print("Matrix A:")
    print(A)
    print("\nMatrix B:")
    print(B)

    # Addition
    print("\nMatrix Addition (A + B):")
    print(A + B)

    # Multiplication
    print("\nMatrix Multiplication (A * B):")
    print(np.dot(A, B))

    # Rank
    print(f"\nRank of A: {np.linalg.matrix_rank(A)}")
    print(f"Rank of B: {np.linalg.matrix_rank(B)}")

    # Determinant
    print(f"\nDeterminant of A: {np.linalg.det(A):.2f}")
    print(f"Determinant of B: {np.linalg.det(B):.2f}")

    # Inverse (if possible)
    try:
        print("\nInverse of A:")
        print(np.linalg.inv(A))
    except np.linalg.LinAlgError:
        print("\nMatrix A is not invertible.")

    try:
        print("\nInverse of B:")
        print(np.linalg.inv(B))
    except np.linalg.LinAlgError:
        print("\nMatrix B is not invertible.")

# Create two 3x3 matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Perform operations
matrix_operations(A, B)

# Explanation
print("\nExplanation:")
print("1. We defined a function to perform various matrix operations on two input matrices.")
print("2. The function demonstrates addition, multiplication, rank calculation, determinant calculation, and inverse (if possible).")
print("3. This approach allows us to easily apply these operations to any pair of matrices.")
print("4. Note that some operations (like inverse) may not be possible for all matrices, so we use try-except blocks to handle these cases.")

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition (A + B):
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication (A * B):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Rank of A: 2
Rank of B: 2

Determinant of A: 0.00
Determinant of B: 0.00

Inverse of A:

Matrix A is not invertible.

Inverse of B:

Matrix B is not invertible.

Explanation:
1. We defined a function to perform various matrix operations on two input matrices.
2. The function demonstrates addition, multiplication, rank calculation, determinant calculation, and inverse (if possible).
3. This approach allows us to easily apply these operations to any pair of matrices.
4. Note that some operations (like inverse) may not be possible for all matrices, so we use try-except blocks to handle these cases.
